# Page settings

baseurl = "https://example.org/"
languageCode = "en-us"
title = "Hugo Theme Doors"
copyright = "© Hugo Theme Doors"
googleAnalytics = "UA-xxxxxxxx-x"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-theme-doors"

disableRSS = true
disableSitemap = true
disable404 = true

# Site information
[params]
description = ""
ogimage = "images/work1.jpg"

# Project section
[params.projects]

[[params.projects.list]]
title = "Инструментарий"
url = "#"
description = "Мои методы исследования и решения ваших задач"
image = "images/work1.jpg"
w = "780"
h = "518"

# Subproject section
[params.subprojects]

[[params.subprojects.list]]
title = "Мне доверяют"
url = "#"
description = "Рекомендации партнёров и клиентов"
image = "images/work2.jpg"
w = "780"
h = "522"

[[params.subprojects.list]]
title = "Мой путь"
url = "#"
description = "История моего опыта"
image = "images/work3.jpg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "The work 4"
url = "#"
description = "Sed do eiusmod tempor incididunt"
image = "images/work4.jpg"
w = "780"
h = "518"

# Contact section
[params.contact]
description = "I would like to hear from you. Please contact me via email or social media."
twitter = "#"
facebook = ""
linkedin = "#"
instagram = "#"
github = ""
email = "#"
